type Query {
    film(id: ID!): Film!
    films: [Film!]!
    director(id: ID!): Director!
    directors: [Director!]!
    actor(id: ID!): Actor!
    actors: [Actor!]!
    writer(id: ID!): Writer!
    writers: [Writer!]!
}

interface Person {
    id: ID!
    name: String!
    dob: String
    nationality: String
}

type Film {
    id: ID!
    title: String!
    description: String
    releaseDate: String
    director: Director!
    genre: String
    rating: Float
    actors: [Actor!]!
    writers: [Writer!]
}

type Director implements Person {
    id: ID!
    name: String!
    dob: String
    nationality: String
    films: [Film!]!
}

type Actor implements Person {
    id: ID!
    name: String!
    dob: String
    nationality: String
    films: [Film!]!
}

type Writer implements Person {
    id: ID!
    name: String!
    dob: String
    nationality: String
    films: [Film!]!
}